"""3

Revision ID: 709f9bb85ccf
Revises: a7c0c195f103
Create Date: 2023-10-28 11:01:41.948371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709f9bb85ccf'
down_revision = 'a7c0c195f103'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
