"""2

Revision ID: a7c0c195f103
Revises: eddcbc9ca926
Create Date: 2023-10-28 10:44:27.676668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7c0c195f103'
down_revision = 'eddcbc9ca926'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('nama_barang', sa.Text(), nullable=False))
    op.add_column('models', sa.Column('harga_barang', sa.Integer(), nullable=False))
    op.add_column('models', sa.Column('kategori_barang', sa.Text(), nullable=False))
    op.add_column('models', sa.Column('gambar_barang', sa.Text(), nullable=False))
    op.add_column('models', sa.Column('deskripsi_barang', sa.Text(), nullable=False))
    op.add_column('models', sa.Column('nama_penjual', sa.Text(), nullable=False))
    op.add_column('models', sa.Column('kontak_penjual', sa.Integer(), nullable=False))
    op.add_column('models', sa.Column('alamat_penjual', sa.Text(), nullable=False))
    op.add_column('models', sa.Column('nama_pembeli', sa.Text(), nullable=True))
    op.add_column('models', sa.Column('kontak_pembeli', sa.Integer(), nullable=True))
    op.add_column('models', sa.Column('alamat_pembeli', sa.Text(), nullable=True))
    op.drop_index('my_index', table_name='models', mysql_length={'name': 255})
    op.drop_column('models', 'value')
    op.drop_column('models', 'name')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('name', mysql.TEXT(), nullable=True))
    op.add_column('models', sa.Column('value', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('my_index', 'models', ['name'], unique=False, mysql_length={'name': 255})
    op.drop_column('models', 'alamat_pembeli')
    op.drop_column('models', 'kontak_pembeli')
    op.drop_column('models', 'nama_pembeli')
    op.drop_column('models', 'alamat_penjual')
    op.drop_column('models', 'kontak_penjual')
    op.drop_column('models', 'nama_penjual')
    op.drop_column('models', 'deskripsi_barang')
    op.drop_column('models', 'gambar_barang')
    op.drop_column('models', 'kategori_barang')
    op.drop_column('models', 'harga_barang')
    op.drop_column('models', 'nama_barang')
    # ### end Alembic commands ###
