"""5

Revision ID: 38557b37030f
Revises: f3dd6a4a4ee6
Create Date: 2023-10-28 11:33:35.076674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38557b37030f'
down_revision = 'f3dd6a4a4ee6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('barang', 'harga_barang',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('barang', 'kontak_penjual',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('barang', 'kontak_pembeli',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('barang', 'kontak_pembeli',
               existing_type=sa.Text(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('barang', 'kontak_penjual',
               existing_type=sa.Text(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.alter_column('barang', 'harga_barang',
               existing_type=sa.Text(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    # ### end Alembic commands ###
