"""4

Revision ID: f3dd6a4a4ee6
Revises: 709f9bb85ccf
Create Date: 2023-10-28 11:13:16.817409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3dd6a4a4ee6'
down_revision = '709f9bb85ccf'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_barang', sa.Text(), nullable=False),
    sa.Column('harga_barang', sa.Integer(), nullable=False),
    sa.Column('kategori_barang', sa.Text(), nullable=False),
    sa.Column('gambar_barang', sa.Text(), nullable=False),
    sa.Column('deskripsi_barang', sa.Text(), nullable=False),
    sa.Column('nama_penjual', sa.Text(), nullable=False),
    sa.Column('kontak_penjual', sa.Integer(), nullable=False),
    sa.Column('alamat_penjual', sa.Text(), nullable=False),
    sa.Column('nama_pembeli', sa.Text(), nullable=True),
    sa.Column('kontak_pembeli', sa.Integer(), nullable=True),
    sa.Column('alamat_pembeli', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_barang'))
    )
    op.drop_table('models')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nama_barang', mysql.TEXT(), nullable=False),
    sa.Column('harga_barang', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('kategori_barang', mysql.TEXT(), nullable=False),
    sa.Column('gambar_barang', mysql.TEXT(), nullable=False),
    sa.Column('deskripsi_barang', mysql.TEXT(), nullable=False),
    sa.Column('nama_penjual', mysql.TEXT(), nullable=False),
    sa.Column('kontak_penjual', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('alamat_penjual', mysql.TEXT(), nullable=False),
    sa.Column('nama_pembeli', mysql.TEXT(), nullable=True),
    sa.Column('kontak_pembeli', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('alamat_pembeli', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('barang')
    # ### end Alembic commands ###
